In [1]:
import pandas as pd

In [2]:
import json, os
path = 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'

In [3]:
with open('COVID-19-master/csse_covid_19_data/country_convert.json', 'r', encoding='utf-8-sig') as json_file:
    json_data = json.load(json_file)

In [43]:
def country_name_convert(row):
    if row['Country_Region'] in json_data:
        return json_data[row['Country_Region']]
    return row['Country_Region']

def create_dateframe(filename):
    
    doc = pd.read_csv(path + filename, encoding = 'utf8')
    try:
        doc = doc[['Country_Region','Deaths']]
    except:
        doc = doc[['Country/Region','Deaths']]
        doc.columns = ['Country_Region','Deaths']
    doc = doc.dropna(subset=['Deaths'])
    doc['Country_Region']  = doc.apply(country_name_convert, axis=1)
    doc =  doc.astype({'Deaths':'int'})
    doc = doc.groupby('Country_Region').sum()
    
    date_column = filename.split('.')[0].lstrip('0').replace('-','/')
    doc.columns = [date_column]
    
    return doc

In [44]:
df = pd.read_csv('COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/04-22-2020.csv')

In [45]:
df.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-22 23:30:53,34.223334,-82.461707,22,0,0,22,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-22 23:30:53,30.295065,-92.414197,117,7,0,110,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-22 23:30:53,37.767072,-75.632346,59,1,0,58,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-22 23:30:53,43.452658,-116.241552,622,12,0,610,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-22 23:30:53,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [46]:
abc = '04-22-2020.csv'

ddd = abc.split('.')[0].lstrip('0').replace('-','/')

ddd

'4/22/2020'

In [52]:
import os

def generate_dateframe(path):
    file_list, csv_list = os.listdir(path), list()
    
    first_doc = True
    for file in file_list:
        if file.split('.')[-1] =='csv':
            csv_list.append(file)
    csv_list.sort()
    
    for file in csv_list:
        doc = create_dateframe(file)
        if first_doc:
            final_doc, first_doc = doc , False
        else:
            final_doc = pd.merge(final_doc, doc, how='outer', left_index= True, right_index=True)
    final_doc= final_doc.fillna(0)
    return final_doc

In [59]:

df_confirmed = generate_dateframe(path)
df_confirmed=df_confirmed.astype(int)

df_confirmed['Country_Flag']='https://s3.orbi.kr/data/file/united/e533d1c052be4ae83b34ddf643989ae0.jpg'

cols = df_confirmed.columns.tolist()
cols.remove('Country_Flag')
cols.insert(1,'Country_Flag')

df_confirmed=df_confirmed[cols]

df_confirmed.to_csv('COVID-19-master/final.csv')

In [56]:
df_confirmed.head()

,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,1/31/2020,...,6/08/2020,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
Country_Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,369.0,384.0,405.0,426.0,446.0,451.0,471.0,478.0,491.0,504.0
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.0,34.0,34.0,35.0,36.0,36.0,36.0,36.0,37.0,38.0
Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,715.0,724.0,732.0,741.0,751.0,760.0,767.0,777.0,788.0,799.0
Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,51.0,51.0,51.0,51.0,51.0,51.0,51.0,51.0,52.0,52.0
Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,5.0,5.0,6.0,6.0,6.0,6.0,7.0